title: theawless
title_separator: "·"
email: theawless.github.io
twitter_username: theawless
github_username: theawless
minimal_mistakes_skin: dirt
search: true

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 10
paginate_path: /page:num/

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Abhinav Singh"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "I like food, football, and FOSS."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/theawless"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/theawless"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

comments:
  provider               : "disqus"
  disqus:
    shortname            : theawless-github-io

analytics:
  provider: "google-gtag"
  google:
    tracking_id          : UA-85757947-1
